- name: Vim
  hosts: localhost
  tasks:
    - name: Vim autoload
      file:
        path: ~/.vim/autoload
        state: directory

    - name: Install vim-pathogen
      get_url:
        url: https://tpo.pe/pathogen.vim
        dest: ~/.vim/autoload/pathogen.vim
        mode: 0640

    - name: Install python3-pip
      become: true
      apt:
        name: python3-pip

    - name: Install powerline
      pip:
        name: powerline-status

    - name: Install supertab
      git:
        repo: https://github.com/ervandew/supertab
        dest: ~/.vim/bundle/supertab

    - name: Install solarized
      git:
        repo: https://github.com/altercation/vim-colors-solarized
        dest: ~/.vim/bundle/vim-colors-solarized

    - name: Install ripgrep
      git:
        repo: https://github.com/jremmen/vim-ripgrep
        dest: ~/.vim/bundle/vim-ripgrep

    - name: Install vim-sensible
      git: 
        repo: https://github.com/tpope/vim-sensible
        dest: ~/.vim/bundle/vim-sensible

    - name: Install FZF
      become: true
      apt:
        name: fzf

    - name: Install fzf in bundle
      git:
        repo: https://github.com/junegunn/fzf
        dest: ~/.vim/bundle/fzf

    - name: Install fzf.vim
      git:
        repo: https://github.com/junegunn/fzf.vim
        dest: ~/.vim/bundle/fzf-vim
